name: Deploy to Reg.ru via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH and Deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
        run: |
          # 1. Создаем скрытую папку для ключей
          mkdir -p ~/.ssh
          
          # 2. Кладем твой секретный ключ в файл и даем правильные права
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          
          # 3. Жестко отключаем проверку Host Key
          echo -e "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
          
          # 4. Запускаем копирование файлов
          rync -avz --delete --chmod=D755,F644 --exclude '.git' --exclude '.github' -e "ssh -o StrictHostKeyChecking=no" ./ ${SSH_USERNAME}@${SSH_HOST}:~/www/isbadmaev.ru/